import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
          <nav className="flex justify-between max-w-7xl mx-auto">
            <div className="flex gap-2">
              <Link href={""}>Icon</Link>
              <Link href={""}>Logo</Link>
            </div>
            <div className="flex gap-4">
              <Link href={""}>Home</Link>
              <Link href={""}>About</Link>
              <Link href={""}>Project</Link>
              <Link href={""}>Contact</Link>
            </div>
          </nav>
            <main className="max-w-7xl mx-auto">{children}</main>
         </body>
      </html>
   );
}
